services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=creator_lucid_studio_local
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=password
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   command: ["sh", "-c", 'redis-server --requirepass "$REDIS_PASSWORD"']
  #   env_file: .env
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "127.0.0.1:6379:6379"

volumes:
  # storage_data:
  postgres_data:
  # redis_data:
