/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  JobAnalysisManagers: () => import('#controllers/job_analysis_managers_controller'),
  Onboard: () => import('#controllers/onboard_controller'),
  Users: () => import('#controllers/users_controller'),
}
